
# everything about data
data:
  category: "pair_3d"
  target_type: "Label" # or "Image
  data_path: "/mnt/data/xyz.csv"
  # data_path: "/mnt/data/trainset"
  # data_path:
  #   source_path:
  #   target_path:
  #   costmap_path: optional
  #   image_type: "tiff"
  dataloader_params:
    batch_size: 4
    pin_memory: True
    shuffle: True
    num_workers: 4
  train_val_ratio: 0.2
  preprocess:
    - module_name: torchio
      func_name: RescaleIntensity
      params:
        out_min_max: (-1, 1)
    - module_name: torchio
      func_name: CropOrPad
      params:
        target_shape: (70, 1000, 1000)
    - module_name: torchio
      func_name: OneHot
      params:
        num_classes: 2
  augmentation:
    - module_name: torchio
      func_name: RandomAffine
      params:
        p: 0.5
# model
model:
  category: FCN
  net:
    module_name: monai.networks.nets
    func_name: UNet
    params:
      spatial_dims: 3
      in_channels: 1
      out_channels: 3,
      channels: (8, 16, 32, 64),
      strides: (2, 2, 2)
  criterion:
    module_name: monai.losses
    func_name: DiceCELoss
    params:
      softmax: True
  optimizer:
    module_name: torch.optim
    func_name: AdamW
    params:
      betas: (0.9, 0.999)
      weight_decay: 0.01
      lr: 0.000001
# training
trainer:
  params:
    gpus: 1
    precision: 16
  callbacks:
    - module_name: pytorch_lightning.callbacks.early_stopping
      func_name: EarlyStopping
      parms:
        monitor: 'val_loss'
    