data:
  category: "pair"
  spatial_dims: 2
  input: 
    dir: "/mnt/eternus/users/Sai/paired_data/pix2pix_test/pix2pix_test_images"
    params:
      data_type: "tiff"
    reader_params:
      dimension_order_out: "ZYX"
      Z: [0]
      C: 0
      T: 0
  output:
    path: "/mnt/eternus/users/Sai/paired_data/pix2pix_pred/pix2pixHD_results_Lambda_100_batch_size_8_4_317_epochs/pix2pix_test_pred"
    suffix: "pred_p2p_DCE"
  dataloader_params:
    batch_size: 8
    num_workers: 1
  preprocess:
    - module_name: torchio
      func_name: ZNormalization
    # - module_name: torchio
    #   func_name: CropOrPad
    #   params:
    #     target_shape: [1024, 1024, 1]
  augmentation:
    - module_name: torchio
      func_name: RandomFlip

model:
  category: pix2pix
  generator_net :
    module_name: mmv_im2im.models.pix2pixHD_generator_discriminator_2D
    func_name: Generator
    params: 
      input_ch: 1
      output_ch: 1
      n_downsample: 4
      n_residual: 9
  discriminator_net:
    module_name: mmv_im2im.models.pix2pixHD_generator_discriminator_2D
    func_name: Discriminator
    params:
      input_ch: 1
      output_ch: 1
      n_D: 2
  # sliding_window_params: None
  # Lambda: 10
  # loss_function:
  #   module_name: mmv_im2im.utils.pix2pix_losses
  #   func_name: Pix2PixHD_loss
  ckpt:
    checkpoint_path:  /mnt/eternus/users/Sai/mmv_im2im_original/pix2pixHD_model_batch_size_8_4_Lambda_100_epoch_317.ckpt
    # checkpoint_path: "/mnt/eternus/users/Sai/mmv_im2im_original/lightning_logs/version_82/checkpoints/epoch=199-step=157799.ckpt"
    hparams_file: "/mnt/eternus/users/Sai/mmv_im2im_original/lightning_logs/version_79/hparams.yaml"

run:
  gpus: 1
  precision: 16
