data:
  category: "pair"
  spatial_dims: 2
  input: 
    dir: "/mnt/eternus/users/Sai/paired_data/pix2pix_small_dataset_test"
    params:
      data_type: "tiff"
    reader_params:
      dimension_order_out: "ZYX"
      Z: [0]
      C: 0
      T: 0
  output:
    path: "/mnt/eternus/users/Sai/paired_data/pix2pix_small_dataset_pred"
    suffix: "pred_LMNB1"
  dataloader_params:
    batch_size: 8
    num_workers: 1
  preprocess:
    - module_name: torchio
      func_name: ZNormalization
    # - module_name: torchio
    #   func_name: CropOrPad
    #   params:
    #     target_shape: [1024, 1024, 1]
  augmentation:
    - module_name: torchio
      func_name: RandomFlip

model:
  category: pix2pixHD
  generator_net :
    module_name: mmv_im2im.models.pix2pixHD_generator_discriminator_2D
    func_name: Generator
    params: 
      input_ch: 1
      output_ch: 1
      n_downsample: 4
      n_residual: 9
  discriminator_net:
    module_name: mmv_im2im.models.pix2pixHD_generator_discriminator_2D
    func_name: Discriminator
    params:
      input_ch: 1
      output_ch: 1
      n_D: 2
  ckpt:
    checkpoint_path: "/mnt/eternus/users/Sai/mmv_im2im_original/pix2pixHD_model_2d_600_state.ckpt"
    hparams_file: "/mnt/eternus/users/Sai/mmv_im2im_original/lightning_logs/version_79/hparams.yaml"

run:
  gpus: 1
  precision: 16
