
# data
data:
  category: "pair_3d"
  # data_path: "/mnt/data/xyz.csv"
  # data_column: "raw_path"
  input: 
    dir: "/mnt/eternus/users/Sai/paired_dataset/segmentation_test_data_sample"
    params:
      data_type: "tif"
    reader_params:
      dimension_order_out: "CZYX"
      C: [0]
      T: 0
  output:
    path: "/mnt/eternus/users/Sai/paired_dataset/segmetation_prediction_data"
    suffix: "pred_LMNB1"
  dataloader_params:
    batch_size: 1
    num_workers: 1
  preprocess:
  - module_name: torchio
    func_name: ZNormalization
# model
model:
  category: FCN
  net:
    module_name: monai.networks.nets
    func_name: UNet
    params:
      spatial_dims: 3
      in_channels: 1
      out_channels: 2
      channels: [16, 32, 64, 128]
      strides: [2, 2, 2]
      num_res_units: 2

  sliding_window_params:
    dims_max: [1, 32, 256, 256]
    overlaps: [0, 8, 16, 16]
  ckpt:
    checkpoint_path: /mnt/eternus/users/mmv_im2im_dev/unet_model_patch_32_256_256_400_with_val_loss_0.3130553364753723_state.ckpt
    hparams_file: /mnt/eternus/users/Sai/mmv_im2im_dev/lightning_logs/version_524/hparams.yaml
# # inference
run:
  gpus: 1
  precision: 16
