
# everything about data
data:
  # data_path: "/mnt/data/xyz.csv"
  # data_column: "raw_path"
  input: 
    dir: "~/ambiomgroupdrive/Jianxu/data/labelfree_lamin/test_data"
    params:
      data_type: "tiff"
  output:
    path: "~/ambiomgroupdrive/Jianxu/data/labelfree_lamin/test_data_prediction"
    suffix: "pred_LMNB1"
  dataloader_params:
    batch_size: 2
    num_workers: 2
  preprocess:
    - module_name: torchio
      func_name: ZNormalization
      params:
# model
model:
  category: FCN
  net:
    module_name: monai.networks.nets
    func_name: UNet
    params:
      spatial_dims: 3
      in_channels: 1
      out_channels: 1
      channels: [8, 16, 32, 64]
      strides: [2, 2, 2]
  ckpt:
    checkpoint_path: ~/ambiomgroupdrive/Jianxu/projects/mmv_im2im/lightning_logs/version_0/checkpoints/epoch=22-step=114.ckpt
    hparams_file: ~/ambiomgroupdrive/Jianxu/projects/mmv_im2im/lightning_logs/version_0/hparams.yaml
# inference
run:
  gpus: 1
  precision: 16
