
# everything about data
data:
  # data_path: "/mnt/data/xyz.csv"
  # data_column: "raw_path"
  spatial_dims: 3
  input: 
    dir: "~/ambiomgroupdrive/Jianxu/data/labelfree_lamin/test_data"
    params:
      data_type: "tiff"
    reader_params:
      dimension_order_out: "CZYX"
      C: [0]
      T: 0
  output:
    path: "~/ambiomgroupdrive/Jianxu/data/labelfree_lamin/test_data_prediction"
    suffix: "pred_LMNB1"
  dataloader_params:
    batch_size: 1
    num_workers: 1
  preprocess:
    - module_name: torchio
      func_name: ZNormalization
# model
model:
  category: FCN
  net:
    module_name: monai.networks.nets
    func_name: UNet
    params:
      spatial_dims: 3
      in_channels: 1
      out_channels: 1
      channels: [8, 16, 32, 64]
      strides: [2, 2, 2]
  sliding_window_params:
    dims_max: [1, 32, 128, 128]
    overlaps: [0, 6, 12, 12]
  ckpt:
    checkpoint_path: ~/ambiomgroupdrive/Jianxu/projects/mmv_im2im/lightning_logs/version_1/checkpoints/epoch=60-step=10979.ckpt
    hparams_file: ~/ambiomgroupdrive/Jianxu/projects/mmv_im2im/lightning_logs/version_1/hparams.yaml
# inference
run:
  gpus: 1
  precision: 16
