
# everything about data
data:
  # data_path: "/mnt/data/xyz.csv"
  # data_column: "raw_path"
  input: 
    dir: "~/ambiomgroupdrive/Sai/data/paired_dataset/test_data"
    params:
      data_type: "tiff"
    reader_params:
      dimension_order_out: "CZYX"
      C: [1]
      T: 1
  output:
    path: "~/ambiomgroupdrive/Sai/data/paired_dataset/test_data_prediction"
    suffix: "pred_LMNB1"
  dataloader_params:
    batch_size: 1
    num_workers: 1
  preprocess:
    - module_name: torchio
      func_name: ZNormalization
# model
model:
#  category: FCN
#  net:
#    module_name: monai.networks.nets
#    func_name: UNet
#    params:
#      spatial_dims: 3
#      in_channels: 1
#      out_channels: 1
#      channels: [8, 16, 32, 64]
#      strides: [2, 2, 2]
#  sliding_window_params:
#    dims_max: [1, 6, 128, 128]
#    overlaps: [0, 6, 12, 12]
#  ckpt:
#    checkpoint_path: ~/ambiomgroupdrive/Jianxu/projects/mmv_im2im/lightning_logs/version_0/checkpoints/epoch=294-step=53099.ckpt
#    hparams_file: ~/ambiomgroupdrive/Jianxu/projects/mmv_im2im/lightning_logs/version_0/hparams.yaml

    
  category: pix2pixGAN
  generator_net :
    module_name: mmv_im2im.models.pix2pix_generator_discriminator_3D
    func_name: UNetGenerator
    params: 
      in_channels: 1
      out_channels: 1

  discriminator_net:
    module_name: mmv_im2im.models.pix2pix_generator_discriminator_3D
    func_name: Discriminator
    params:
      in_channels: 1

  sliding_window_params:
    dims_max: [1, 32, 128, 128]
    overlaps: [0, 6, 12, 12]
  ckpt:
    checkpoint_path: ~/ambiomgroupdrive/Sai/mmv_im2im_fork/lightning_logs/version_228/checkpoints/epoch=19-step=3199.ckpt
    hparams_file: ~/ambiomgroupdrive/Sai/mmv_im2im_fork/lightning_logs/version_228/hparams.yaml
# inference
run:
  gpus: 1
  precision: 16
