
# everything about data
data:
  category: "embedseg"
  data_path:  "/mnt/eternus/users/Jianxu/data/embedseg/train/"
  cache_path: "/mnt/eternus/users/Jianxu/data/embedseg/train_cache/"
  dataloader:
    train_val_ratio: 0.1
    train:
      dataloader_type:
        module_name: monai.data
        func_name: PersistentDataset
      dataset_params: 
        cache_dir: "./tmp"
      dataloader_params:
        batch_size: 4
        pin_memory: True
        num_workers: 4
      partial_loader:
        load_percentage: 0.2
    val:
      dataloader_type:
        module_name: monai.data
        func_name: PersistentDataset
      dataset_params: 
        cache_dir: "./tmp"
      dataloader_params:
        batch_size: 1
        pin_memory: True
        num_workers: 3
  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM", "GT", "CE", "CL"]
        dimension_order_out: "YX"
        C: 0
        T: 0
        Z: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT", "CE", "CL"]
    - module_name: monai.transforms
      func_name: NormalizeIntensityd
      params:
        keys: ["IM"]
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT", "CE", "CL"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT", "CE", "CL"]


# model
model:
  category: embedseg
  net:
    module_name: mmv_im2im.models.nets.BranchedERFNet_2d
    func_name: BranchedERFNet_2d
    params:
      num_classes: [4, 1]
      input_channels: 1
  criterion:
    module_name: mmv_im2im.utils.embedding_loss
    func_name: SpatialEmbLoss_2D
    params:
      grid_y: 1024
      grid_x: 1024
      pixel_y: 1
      pixel_x: 1
      n_sigma: 2
      foreground_weight: 1
  optimizer:
    module_name: torch.optim
    func_name: Adam  # AdamW
    params:
      lr: 0.001
# training
training:
  params:
    gpus: 4
    precision: 16
    reload_dataloaders_every_n_epochs: 10
    #stochastic_weight_avg: True

    