mode: train

data:
  category: "embedseg"
  data_path: ./data/instance3D/train_fbl
  dataloader:
    train:
      dataloader_params:
        batch_size: 1
        pin_memory: True
        num_workers: 4 #4
        persistent_workers: True

  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM"]
        dtype: float
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["GT"]
        dtype: short
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT"]
    - module_name: monai.transforms
      func_name: NormalizeIntensityd
      params:
        keys: ["IM"] 
    - module_name: monai.transforms
      func_name: DivisiblePadd
      params:
        keys: ["IM", "GT"]
        k: 8
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandSpatialCropSamplesd
      params:
        keys: ["IM", "GT"]
        random_size: False
        num_samples: 1
        roi_size: [32, 512, 512]
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT"]
   
model:
  framework: embedseg
  model_extra:
    center_method: "centroid"
    pre-train: ./lightning_logs/version_152/checkpoints/last.ckpt  #26 # 50
    validation_sliding_windows:
      roi_size: [32, 512, 512]
      sw_batch_size: 1
      overlap: 0.6
      mode: "gaussian"
  net:
    module_name: aicsmlsegment.NetworkArchitecture.unet_xy_zoom_0pad_single
    func_name: UNet3D
    params:
      in_channel: 1
      n_classes: 7
      down_ratio: 2
  criterion:
    module_name: mmv_im2im.utils.embedding_loss
    func_name: SpatialEmbLoss_3d
    params:
      grid_y: 1024
      grid_x: 1024
      grid_z: 128
      pixel_y: 1
      pixel_x: 1
      pixel_z: 1
      n_sigma: 3
      min_mask_sum: 64
      min_unclustered_sum: 1
      min_object_size: 3
      foreground_weight: 64
      use_costmap: False
  optimizer:
      module_name: torch.optim
      func_name: Adam  # AdamW
      params:
        lr: 0.00001
  scheduler:
      module_name: torch.optim.lr_scheduler
      func_name: ExponentialLR
      params:
        gamma: 0.99
trainer:
  verbose: True
  params:
    accelerator: "gpu"
    devices: 2
    precision: 16
    max_epochs: 500
    detect_anomaly: True
    gradient_clip_val: 0.8
  callbacks:
    # - module_name: pytorch_lightning.callbacks.early_stopping
    #   func_name: EarlyStopping
    #   params:
    #     monitor: 'val_loss'
    #     patience: 50
    #     verbose: True
    #     mode: 'max'
    - module_name: pytorch_lightning.callbacks.model_checkpoint
      func_name: ModelCheckpoint
      params:
        monitor: 'val_loss'
        filename: '{epoch}-{val_loss:.5f}'
        save_top_k: 2
        save_last: True
        save_weights_only: True 
        mode: 'max'