mode: train

data:
  category: "embedseg"
  data_path: /mnt/eternus/users/Jianxu/projects/im2im_experiments_v1/data/instance3D/train_bf
  cache_path: /mnt/eternus/users/Jianxu/projects/im2im_experiments_v1/data/instance3D/cache_bf
  extra:
    center_method: "centroid"
  dataloader:
    train:
      dataloader_params:
        batch_size: 1
        pin_memory: True
        num_workers: 4 #4
        persistent_workers: True

  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM", "CM"]
        dtype: float32
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["GT"]
        dtype: short
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["CL"]
        dtype: ubyte
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["CE"]
        dtype: bool
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT", "CE", "CL", "CM"]
    - module_name: mmv_im2im.preprocessing.transforms
      func_name: norm_around_center
      params:
        keys: ["IM"]
        min_z: 32  
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT", "CE", "CL", "CM"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT", "CE", "CL", "CM"]
   
model:
  framework: embedseg
  model_extra:
    validation_sliding_windows:
      roi_size: [32, 512, 512]
      sw_batch_size: 1
      overlap: 0.6
      mode: "gaussian"
  net:
    module_name: aicsmlsegment.NetworkArchitecture.unet_xy_zoom_0pad_single
    func_name: UNet3D
    params:
      in_channel: 1
      n_classes: 7
      down_ratio: 4
  criterion:
    module_name: mmv_im2im.utils.embedding_loss
    func_name: SpatialEmbLoss_3d
    params:
      grid_y: 1024
      grid_x: 1024
      grid_z: 128
      pixel_y: 1
      pixel_x: 1
      pixel_z: 1
      n_sigma: 3
      foreground_weight: 4.5
      use_costmap: True
      min_mask_sum: 128
      min_object_size: 36
  optimizer:
      module_name: torch.optim
      func_name: Adam  # AdamW
      params:
        lr: 0.0001
  scheduler:
      module_name: torch.optim.lr_scheduler
      func_name: ExponentialLR
      params:
        gamma: 0.98
trainer:
  verbose: True
  params:
    accelerator: "gpu"
    devices: 4
    precision: 16
    max_epochs: 250
    detect_anomaly: True
    gradient_clip_val: 0.8
    check_val_every_n_epoch: 5
    num_sanity_val_steps: 0
  callbacks:
    # - module_name: lightning.pytorch.callbacks.model_checkpoint
    #   func_name: ModelCheckpoint
    #   params:
    #     save_last: True
    #     save_weights_only: True 
    - module_name: lightning.pytorch.callbacks.early_stopping
      func_name: EarlyStopping
      params:
        monitor: 'val_loss'
        patience: 10        
    # - module_name: lightning.pytorch.callbacks.model_checkpoint
    #   func_name: ModelCheckpoint
    #   params:
    #     monitor: 'val_loss'
    #     filename: '{epoch}-{val_loss:.5f}'
    #     save_top_k: 5
    #     save_last: True
    #     save_weights_only: True 
    - module_name: lightning.pytorch.callbacks.model_checkpoint
      func_name: ModelCheckpoint
      params:
        monitor: 'val_loss'
        filename: 'best'
        save_top_k: 1
        save_last: True
        save_weights_only: True     
    - module_name: lightning.pytorch.callbacks.model_checkpoint
      func_name: ModelCheckpoint
      params:
        save_weights_only: True
        every_n_epochs: 5 
        save_top_k: -1                        