mode: train

data:
  category: "pair"
  data_path: ./data/semantic3D/train_fbl/ 
  dataloader:
    train:
      dataloader_params:
        batch_size: 1
        pin_memory: True
        num_workers: 4

  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM"]
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["GT"]
        dtype: int
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT"]
    - module_name: monai.transforms
      func_name: NormalizeIntensityd
      params:
        keys: ["IM"]
    - module_name: monai.transforms
      func_name: RandSpatialCropSamplesd
      params:
        keys: ["IM", "GT"]
        random_size: False
        num_samples: 1
        roi_size: [32, 512, 512]
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT"]
    - module_name: monai.transforms
      func_name: RandHistogramShiftd
      params:
        prob: 0.2
        keys: ["IM"]

model:
  framework: FCN
  net:
    module_name: monai.networks.nets
    func_name: DynUnet
    params:
      spatial_dims: 3
      in_channels: 1
      out_channels: 2
      strides: [[1, 1, 1], [1, 2, 2], [1, 1, 1], [2, 2, 2]]
      kernel_size: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
      upsample_kernel_size:  [[1, 2, 2], [1, 1, 1], [2, 2, 2]]
      filters: [64, 128, 192, 256]
      dropout: 0.2
      res_block: True
    # module_name: aicsmlsegment.NetworkArchitecture.unet_xy_zoom_0pad_single
    # func_name: UNet3D
    # params:
    #  in_channel: 1
    #  n_classes: 7
    #  down_ratio: 2
  criterion:
    module_name: monai.losses
    func_name: GeneralizedDiceFocalLoss
    params:
      softmax: True
      to_onehot_y: True
    #module_name: torch.nn
    #func_name: CrossEntropyLoss
    #params:
    #  reduction: 'mean'
    #  use_costmap: True
    # module_name: mmv_im2im.utils.basic_losses
    # func_name: PixelWiseCrossEntropyLoss
    # params:
    #   class_weights: [1,2,4,2,2,25,50]
    #   #use_costmap: True
  optimizer:
    module_name: torch.optim
    func_name: Adam  # AdamW
    params:
      lr: 0.001
      weight_decay: 0.0005
  scheduler:
    module_name: torch.optim.lr_scheduler
    func_name: ExponentialLR
    params:
      gamma: 0.98
trainer:
  verbose: True
  params:
    accelerator: "gpu"
    devices: 1
    precision: 16
    max_epochs: 10000
    detect_anomaly: True
  callbacks:
    - module_name: pytorch_lightning.callbacks.early_stopping
      func_name: EarlyStopping
      params:
        monitor: 'val_loss'
        patience: 50 
        verbose: True
    - module_name: pytorch_lightning.callbacks.model_checkpoint
      func_name: ModelCheckpoint
      params:
        monitor: 'val_loss'
        filename: '{epoch}-{val_loss:.5f}'
        save_top_k: 2
        save_last: True
        save_weights_only: True 