mode: train

data:
  category: "pair"
  data_path: /mnt/eternus/users/Jianxu/projects/im2im_experiments_v1/data/synthetic2D/NPM1/train
  dataloader:
    train:
      dataloader_params:
        batch_size: 4
        pin_memory: True
        num_workers: 4

  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM", "GT"]
        dimension_order_out: "YX"
        T: 0
        C: 0
        Z: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT"]          
    - module_name: monai.transforms
      func_name: ScaleIntensityRangePercentilesd
      params:
        keys: ["GT"]
        lower: 0.01
        upper: 99.99
        b_min: -1
        b_max: 1    
    - module_name: monai.transforms
      func_name: ScaleIntensityRangePercentilesd
      params:
        keys: ["IM"]
        lower: 0
        upper: 100
        b_min: -1
        b_max: 1    
    - module_name: monai.transforms
      func_name: RandSpatialCropSamplesd
      params:
        keys: ["IM", "GT"]
        random_size: False
        num_samples: 4
        roi_size: [256, 256]
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT"]

model:
  framework: cyclegan
  net:
    generator:
      type: predefined_resnet
      params:
        spatial_dims: 2
        in_channels: 1
        out_channels: 1
        n_down_blocks: 4
        n_res_blocks: 9
        nf: 64
        norm_layer: "BATCH"  
    discriminator:
      type: predefined_basic
      params:
        spatial_dims: 2
        in_channels: 1
        n_layers: 4
        nf: 64
        norm_layer: "INSTANCE"
  criterion:
    gan_loss:
      module_name: torch.nn
      func_name: MSELoss
      params:
        reduction: 'mean'
    cycle_loss:
      module_name: torch.nn
      func_name: L1Loss
      params:
        reduction: 'mean'
    identity_loss:
      module_name: torch.nn
      func_name: L1Loss
      params:
        reduction: 'mean'
    weights:
      gan_loss: 1
      cycle_loss: 10
      identity_loss: 2
    fake_pool_size: 50
  optimizer:
    generator:
      module_name: torch.optim
      func_name: Adam  # AdamW
      params:
        lr: 0.0002
        betas: [0.5, 0.999]
        weight_decay: 0.0005
    discriminator:
      module_name: torch.optim
      func_name: Adam  # AdamW
      params:
        lr: 0.0002
        betas: [0.5, 0.999]
        weight_decay: 0.0005
  scheduler:
    generator:
      module_name: torch.optim.lr_scheduler
      func_name: ExponentialLR
      params:
        gamma: 0.999
    discriminator:
      module_name: torch.optim.lr_scheduler
      func_name: ExponentialLR
      params:
        gamma: 0.999
trainer:
  verbose: True
  params:
    accelerator: "gpu"
    devices: 1
    precision: 16
    max_epochs: 2000
    detect_anomaly: True
  callbacks:
    - module_name: lightning.pytorch.callbacks.model_checkpoint
      func_name: ModelCheckpoint
      params:
        save_last: True
        save_weights_only: True 