mode: train

data:
  category: "embedseg"
  data_path: /mnt/eternus/project_data/im2im_paper/instance_segmentation_3D/flo_small  
  dataloader:
    train:
      dataloader_params:
        batch_size: 2
        pin_memory: True
        num_workers: 4 #4
        persistent_workers: True

  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM", "CM"]
        dtype: float
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["GT"]
        dtype: short
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT", "CM"]
    - module_name: monai.transforms
      func_name: NormalizeIntensityd
      params:
        keys: ["IM"]
    - module_name: monai.transforms
      func_name: RandSpatialCropSamplesd
      params:
        keys: ["IM", "GT", "CM"]
        random_size: False
        num_samples: 4
        roi_size: [32, 128, 128]
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT", "CM"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT", "CM"]
    - module_name: monai.transforms
      func_name: RandHistogramShiftd
      params:
        prob: 0.25
        keys: ["IM"]
        num_control_points: [3,6]
   
model:
  framework: embedseg
  model_extra:
    center_method: "centroid"
  #model_extra:
  #  pre-train: /mnt/eternus/users/Jianxu/projects/lightning_logs/version_12/checkpoints/last.ckpt
  net:
    module_name: aicsmlsegment.NetworkArchitecture.unet_xy_zoom_0pad_single
    func_name: UNet3D
    params:
      in_channel: 1
      n_classes: 7
      down_ratio: 4
  criterion:
    module_name: mmv_im2im.utils.embedding_loss
    func_name: SpatialEmbLoss_3d
    params:
      grid_y: 1024
      grid_x: 1024
      grid_z: 128
      pixel_y: 1
      pixel_x: 1
      pixel_z: 1
      n_sigma: 3
      foreground_weight: 4.5
      use_costmap: True
  optimizer:
      module_name: torch.optim
      func_name: Adam  # AdamW
      params:
        lr: 0.00001
  scheduler:
      module_name: torch.optim.lr_scheduler
      func_name: ExponentialLR
      params:
        gamma: 0.99
trainer:
  verbose: True
  params:
    gpus: 1
    precision: 16
    max_epochs: 500
    detect_anomaly: True
    gradient_clip_val: 0.8
