mode: train

data:
  category: "embedseg"
  cache_path: /mnt/eternus/users/Justin/im2im_paper/embedseg_new/cache_3d_fluorescent  
  extra:
    center_method: "centroid"
  dataloader:
    train:
      dataloader_params:
        batch_size: 1
        pin_memory: True
        num_workers: 4 #4
        persistent_workers: True

  preprocess:
    #- module_name: monai.transforms
    #  func_name: LoadImaged
    #  params:
    #    keys: ["IM", "GT", "CE", "CL", "CM"]
    #    dimension_order_out: "ZYX"
    #    C: 0
    #    T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM", "CM"]
        dtype: float
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["GT"]
        dtype: short
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["CL"]
        dtype: ubyte
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["CE"]
        dtype: bool
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT", "CE", "CL", "CM"]
    - module_name: monai.transforms
      func_name: NormalizeIntensityd
      params:
        keys: ["IM"] 
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT", "CE", "CL", "CM"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT", "CE", "CL", "CM"]
    - module_name: monai.transforms
      func_name: RandHistogramShiftd
      params:
        prob: 0.25
        keys: ["IM"]
        num_control_points: [3,6]
   
model:
  framework: embedseg
  #model_extra:
  #  pre-train: /mnt/eternus/users/Jianxu/projects/lightning_logs/version_12/checkpoints/last.ckpt
  net:
    module_name: aicsmlsegment.NetworkArchitecture.unet_xy_zoom_0pad_single
    func_name: UNet3D
    params:
      in_channel: 1
      n_classes: 7
      down_ratio: 4
  criterion:
    module_name: mmv_im2im.utils.embedding_loss
    func_name: SpatialEmbLoss_3d
    params:
      grid_y: 1024
      grid_x: 1024
      grid_z: 128
      pixel_y: 1
      pixel_x: 1
      pixel_z: 1
      n_sigma: 3
      foreground_weight: 4.5
      use_costmap: True
  optimizer:
      module_name: torch.optim
      func_name: Adam  # AdamW
      params:
        lr: 0.00001
  scheduler:
      module_name: torch.optim.lr_scheduler
      func_name: ExponentialLR
      params:
        gamma: 0.98
trainer:
  verbose: True
  params:
    gpus: 3
    precision: 16
    max_epochs: 50
    #terminate_on_nan: True
    detect_anomaly: True
    gradient_clip_val: 0.8
  callbacks:
    - module_name: pytorch_lightning.callbacks.early_stopping
      func_name: EarlyStopping
      params:
        monitor: 'val_loss'
        patience: 50
    - module_name: pytorch_lightning.callbacks.model_checkpoint
      func_name: ModelCheckpoint
      params:
        monitor: 'val_loss'
        filename: '{epoch}-{val_loss:.5f}'
        save_top_k: 2
        save_last: True
        save_weights_only: True 
    - module_name: pytorch_lightning.callbacks.model_checkpoint
      func_name: ModelCheckpoint
      params:
        monitor: 'val_loss'
        filename: 'best'