mode: train

data:
  category: "embedseg"
  extra:
    center_method: "centroid"
  dataloader:
    train:
      dataloader_params:
        batch_size: 4
        pin_memory: True
        num_workers: 4

  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM", "GT", "CE", "CL"]
        dimension_order_out: "YX"
        C: 0
        T: 0
        Z: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT", "CE", "CL"]
    - module_name: monai.transforms
      func_name: ScaleIntensityRangePercentilesd
      params:
        keys: ["IM"]
        lower: 0.5
        upper: 99.5
        b_min: -1
        b_max: 1
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT", "CE", "CL"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT", "CE", "CL"]

model:
  framework: embedseg
  net:
    module_name: mmv_im2im.models.nets.BranchedERFNet_2d
    func_name: BranchedERFNet_2d
    params:
      num_classes: [4, 1]
      input_channels: 1
  criterion:
    module_name: mmv_im2im.utils.embedding_loss
    func_name: SpatialEmbLoss_2d
    params:
      grid_y: 1024
      grid_x: 1024
      pixel_y: 1
      pixel_x: 1
      n_sigma: 2
      foreground_weight: 2
  optimizer:
      module_name: torch.optim
      func_name: Adam  # AdamW
      params:
        lr: 0.001
  scheduler:
      module_name: torch.optim.lr_scheduler
      func_name: ExponentialLR
      params:
        gamma: 0.97
trainer:
  verbose: True
  params:
    accelerator: "gpu"
    devices: 1
    precision: 16
    max_epochs: 10000
    detect_anomaly: True
