mode: inference

data:
  inference_input:
    reader_params:
      dimension_order_out: "TYX"
      C: 0
      Z: 0
  preprocess:        
    - module_name: monai.transforms
      func_name: ScaleIntensityRangePercentiles
      params:
        lower: 0.5
        upper: 99.5
        b_min: -1
        b_max: 1
  postprocess:
    - module_name: mmv_im2im.postprocessing.basic_collection
      func_name: extract_segmentation
      params:
        channel: 0
        cutoff: 0.00000001

model:
  framework: pix2pix
  net:
    generator:
      type: predefined_resnet
      params:
        spatial_dims: 2
        in_channels: 1
        out_channels: 1
        n_down_blocks: 4
        n_res_blocks: 9
        nf: 64
        norm_layer: "BATCH"
    discriminator:
      type: predefined_multiscale
      params:
        num_discriminator: 2
        spatial_dims: 2
        in_channels: 2
        n_layers: 4
        nf: 64
        norm_layer: "INSTANCE"
  checkpoint: "/mnt/eternus/users/Jianxu/logs/lightning_logs/version_1/checkpoints/last.ckpt"
  model_extra:
    sliding_window_params:
      roi_size: [1024, 1024]
      sw_batch_size: 4
      overlap: 0.2
      mode: "gaussian"
trainer:
  params:
    accelerator: "gpu"
    devices: 1
    precision: 16
