mode: train

data:
  category: "embedseg"
  extra:
    center_method: "centroid"
  dataloader:
    train:
      dataloader_params:
        batch_size: 2
        pin_memory: True
        num_workers: 4

  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM", "GT", "CE", "CL"]
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT", "CE", "CL"]
    - module_name: monai.transforms
      func_name: ScaleIntensityRangePercentilesd
      params:
        keys: ["IM"]
        lower: 0.1
        upper: 99.9
        b_min: -1
        b_max: 1
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT", "CE", "CL"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT", "CE", "CL"]

model:
  framework: embedseg
  net:
    module_name: mmv_im2im.models.nets.BranchedERFNet_3d
    func_name: BranchedERFNet_3d
    params:
      num_classes: [6, 1]
      input_channels: 1
  criterion:
    module_name: mmv_im2im.utils.embedding_loss
    func_name: SpatialEmbLoss_3d
    params:
      grid_y: 256
      grid_x: 256
      grid_z: 128
      pixel_y: 1
      pixel_x: 1
      pixel_z: 1
      n_sigma: 3
      foreground_weight: 3
  optimizer:
      module_name: torch.optim
      func_name: Adam  # AdamW
      params:
        lr: 0.001
  scheduler:
      module_name: torch.optim.lr_scheduler
      func_name: ExponentialLR
      params:
        gamma: 0.98
trainer:
  verbose: True
  params:
    gpus: 1
    precision: 16
    max_epochs: 10000
    terminate_on_nan: True
