name: Test and Lint

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9, '3.10', 3.11]
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest mmv_im2im/tests/
    - name: Upload codecov
      uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9.15
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 mmv_im2im --count --verbose --show-source --statistics
    #- name: Check with black
    #  run: |
    #    black --check mmv_im2im
